/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IocsRouteImport } from './routes/iocs'
import { Route as CorrelationsRouteImport } from './routes/correlations'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IocsRoute = IocsRouteImport.update({
  id: '/iocs',
  path: '/iocs',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationsRoute = CorrelationsRouteImport.update({
  id: '/correlations',
  path: '/correlations',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/artifacts': typeof ArtifactsRoute
  '/correlations': typeof CorrelationsRoute
  '/iocs': typeof IocsRoute
  '/reports': typeof ReportsRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/artifacts': typeof ArtifactsRoute
  '/correlations': typeof CorrelationsRoute
  '/iocs': typeof IocsRoute
  '/reports': typeof ReportsRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/artifacts': typeof ArtifactsRoute
  '/correlations': typeof CorrelationsRoute
  '/iocs': typeof IocsRoute
  '/reports': typeof ReportsRoute
  '/timeline': typeof TimelineRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/artifacts'
    | '/correlations'
    | '/iocs'
    | '/reports'
    | '/timeline'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/artifacts'
    | '/correlations'
    | '/iocs'
    | '/reports'
    | '/timeline'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/artifacts'
    | '/correlations'
    | '/iocs'
    | '/reports'
    | '/timeline'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ArtifactsRoute: typeof ArtifactsRoute
  CorrelationsRoute: typeof CorrelationsRoute
  IocsRoute: typeof IocsRoute
  ReportsRoute: typeof ReportsRoute
  TimelineRoute: typeof TimelineRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iocs': {
      id: '/iocs'
      path: '/iocs'
      fullPath: '/iocs'
      preLoaderRoute: typeof IocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlations': {
      id: '/correlations'
      path: '/correlations'
      fullPath: '/correlations'
      preLoaderRoute: typeof CorrelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ArtifactsRoute: ArtifactsRoute,
  CorrelationsRoute: CorrelationsRoute,
  IocsRoute: IocsRoute,
  ReportsRoute: ReportsRoute,
  TimelineRoute: TimelineRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
